// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsleepssememukxrdbsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbGVlcHNzZW1lbXVreHJkYnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzQxNzEsImV4cCI6MjA3MDUxMDE3MX0.-Z-7ynF4xle50ZG5S3knaA4Q8LUL4Ir4DBv3aWhOeqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});